### ISSUE TITLE
Mathematical signs are misaligned

### ISSUE THREAD

**Issue by thlinard** [psb1558/Elstob-font#15]
Although this isn't the primary purpose of the font, it would be nice if the vertical alignment could to be corrected. Also, the thickness (and somewhat the length) of the horizontal bar of +÷−¬=≠±≤≥ should be the same.

Test of ×<>+÷−¬=≠±≤≥ with version 1.008:
<img width="1323" alt="Elstob" src="https://user-images.githubusercontent.com/13808824/91088236-f081cf80-e651-11ea-8953-9cb61ebba3dc.png">

The same example in Encode Sans VF 3.002 (default or `lnum` feature) https://github.com/google/fonts/tree/master/ofl/encodesans

<img width="804" alt="Encode Sans" src="https://user-images.githubusercontent.com/13808824/91063368-32991a00-e62e-11ea-9bdb-4a00c3211cbb.png">

**Comment by psb1558** [comment]
Ha ha! They look awful, don't they! I'm so very far from being a mathematician, I've never thought of these as a set, and it has never occurred to me that they ought to be harmonized. But now that I know, I'll work on them.

**Comment by thlinard** [comment]
Thank you!! And if you want to work on an additional refinement, as you have `lnum` and `onum` features: you can vertically align the signs on the figures, according to their style. For example, Encode Sans has two sets of mathematical signs, of different vertical alignment (and different heights, for some glyphs):
<img width="1428" alt="Encode Sans lnum and onum" src="https://user-images.githubusercontent.com/13808824/91148050-640af780-e6b9-11ea-870f-73d09b1e02c3.png">

**Comment by psb1558** [comment]
Thanks, @thlinard: I was thinking about that just this morning, noticing that in Brill, where the default figures are  oldstyle, the operators are aligned between baseline and xheight, while in Garamond Premier Pro, where the default figures are lining, the operators are both larger and higher.

Here's a first stab at a more correct set of operators (positioned for oldstyle figures):
<img width="600" alt="image" src="https://user-images.githubusercontent.com/16215767/91166549-87757880-e6a0-11ea-9236-85c111460bef.png">
As in Brill and GarPrPro, the stroke thickness is about that of a macron, and the gain in weight from regular to bold is relatively modest.

In Brill and GarPrPro the operators remain upright in the italic face, while in Gentium Plus they are skewed. Which is more correct?

**Comment by psb1558** [comment]
With a few oldstyle tabular figures:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/16215767/91168143-20a58e80-e6a3-11ea-89ba-41d222977083.png">

**Comment by thlinard** [comment]
Upright is traditional for operators. See this discussion (specially John Hudson's comments):
https://typedrawers.com/discussion/1246/sloping-math-symbols-in-italic-faces-is-it-normal

And this document:
http://www.typoma.com/publ/20041002-atypi.pdf

And also:
https://en.wikipedia.org/wiki/Typographical_conventions_in_mathematical_formulae

**Comment by psb1558** [comment]
Thanks for the useful links. Hudson's observations (upright but differently spaced in the italic face) make a lot of sense to me; Küster on the "math axis" is very helpful.

Given that this will never be a "math font," but has to handle mathematical expressions that may come up in a largely humanities or linguistic context, what other operators or symbols are necessary? Should the characters cited by Küster
<img width="496" alt="image" src="https://user-images.githubusercontent.com/16215767/91173579-0a500080-e6ac-11ea-90f9-ad7c70f8d6cc.png">
all be included? Are there others?

**Comment by thlinard** [comment]
Usually, non-math fonts don't go beyond the mathematical signs contained in Adobe Latin 2:
~<>=×÷+−¬±^|⁄∂πµ∆Ω∏∑∫√∞≈≠≤≥◊
https://github.com/adobe-type-tools/adobe-latin-charsets

Adobe Latin 5 has vulgar fractions https://en.wikipedia.org/wiki/Number_Forms, superscript and subscript numerals https://en.wikipedia.org/wiki/Superscripts_and_Subscripts_(Unicode_block), some arrows and some additional signs (∟∩≡⌐⟨⟩).

Otherwise, the complete charset is huge:
https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode

So I think for important math needs a user will take a specialized font.

**Comment by psb1558** [comment]
Thanks again. I think I will include the symbols in Adobe Latin 2. I've already got superscript numbers (more for footnotes than for math), but otherwise I see little need for the math stuff in Adobe Latin 5. As you say, anyone serious about math needs a specialized font.

**Comment by marrus-sh** [comment]
For reference, mathematical characters I’ve noticed in linguistics, which seems to be the humanities field most liable to use them:

+ `U+2205 ∅ EMPTY SET` can be used to indicate a “null” word or root. It differs from a slashed zero and `U+00D8 Ø LATIN CAPITAL LETTER O WITH STROKE` in that it is more geometric in design, and completely circular rather than elliptical.

+ Wikipedia tells me that `U+29B0 ⦰ REVERSED EMPTY SET` can be used to avoid confusion in languages in which Ø is a letter, although I cannot personally attest to this.

+ `U+221A √ SQUARE ROOT` (included in Adobe Latin 2) is used to sometimes indicate the root of a word; either “√ROOT” to indicate *any* root, or (for example) “√swim” to indicate the root form of a word (common in languages where words undergo a high degree of mutation).

+ `U+2032 ′ PRIME` and `U+2033 ″ DOUBLE PRIME` are common in syntax diagramming. The evolution of this notation is something like X̅ (i.e., X with overbar) → X¹ → X′ (pronounced “X‐bar” in all cases), but the use of the prime symbol has seemed quite popular. And I have only ever seen X″, not X² or X̿ (X‐double‐overbar).

+ `U+2192 → RIGHTWARDS ARROW` to show evolution of a word (e.g., in etymologies) or transformation of a phrase (“I did like what?” → “What did I like?”). This is probably not essential and using a greater‐than sign is common enough for this.

For charting out the shapes of syllables, there are a number of additional symbols:

+ Numeric subscripts; for example “C₁C₂VC” combined with phrases such as “C₂‐reduplication”. I understand not being too enthusiastic about encoding these :P . “C1C2VC” is probably perfectly comprehensible in a lingustics context (especially with oldstyle numerals), if a bit harder to read.

+ Small Greek letters are used for *parts of syllables* (onset, rime, coda…), whereas upper Latin letters are used for *classes of sound* (consonant, vowel…). Specifically I have noticed the following small Greek letters be used:

    + σ for “Syllable”
    + ι for “Initial”
    + ω for “Onset”
    + φ for “Final”
    + μ for “Medial”
    + ρ for “Rime”
    + ν for “Nucleus”
    + κ for ”Coda”
    + τ for “Tone” (only in tonal languages)

    I’ve never seen uppercase Greek used in linguistics.

+ `U+207A ⁺ SUPERSCRIPT PLUS SIGN` to mean “one or more”, alongside a (high) asterisk meaning “zero or more”. These should have similar metrics. For example, “C⁺VC*” indicates a syllable which begins with one or more consonants, has a single vowel, and ends with zero or more consonants.

**Comment by marrus-sh** [comment]
A few rarer symbols as well, that I have noticed in etymological studies…

+ `U+2AA4 ⪤ GREATER-THAN OVERLAPPING LESS-THAN`, when two etyma are clearly related, but it is not clear which descended from the other.

+ Both `U+223C ∼ TILDE OPERATOR` and `U+2053 ⁓ SWUNG DASH`. The former should have the same metrics as plus sign, minus sign, etc., and is used to show a relation between two things. (My unprofessional opinion is that TILDE OPERATOR should mimic MINUS SIGN, and TILDE should mimic HYPHEN.) SWUNG DASH is significantly wider, and common in dictionaries (as pictured below) to stand in for the term being defined. It is *also* sometimes used in etymologies to show a semantic relation between two etyma.

    ![image](https://user-images.githubusercontent.com/3212430/91220442-0682a500-e6d1-11ea-86e6-a5eae9bc0abc.png)

(Note that none of these symbols are presently in JuniusX, so if you do decide to add them, you may want to add them there as well.)

**Comment by psb1558** [comment]
Thanks, @marrus-sh! This is extremely useful, and most of these characters will to relatively little to increase the size of the font.

I've been quite selective about the Elstob character set (though most or all of these seem to belong); but in JuniusX anything goes: I'll certainly make sure they are all there.

**Comment by psb1558** [comment]
For comment/correction: the non-Greek operators from the Adobe Latin 2 set:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/16215767/91373758-2c996980-e7e5-11ea-9050-51f51e181818.png">

**Comment by thlinard** [comment]
It looks very good!

∅ (EMPTY SET, U+2205) isn't in Adobe Latin 2, but Ø (LATIN CAPITAL LETTER O WITH STROKE, U+00D8). You are of course free to include it. 😀 I don't see its size relative to the figures, it's traditional that it is a little shorter than the lining figures, and aligned with the baseline.

◊ is most often in the math axis (so below the baseline).

∞ inherits the style of the font, so with upstrokes and downstrokes in the case of Elstob. Sometimes aligned with the baseline, but personally I prefer in the math axis.

√ could be aligned with the baseline or below, but much taller than the figures anyway.

≈ could be more in the style of two ~ (but not everyone agrees with this: some argue that it is an "alphabetical" glyph — font-dependent design —, others that it is a geometric glyph — rather font-independent design).

**Comment by psb1558** [comment]
Thanks, Thomas!

For the size and positioning of most of these I was comparing Brill and Gentium, sometimes Source-Serif, Libertine or Garamond Premier Pro, but when they disagree it's hard to decide: some are presumably more math-friendly than others. What fonts are best to look at for math? (I just now found Latin Modern Math, which seems to agree more with what you're suggesting than the others.)

**Comment by alerque** [comment]
If by ‘Libertine’ you mean ‘Linux Libertine’, don't use that as a guide for this issue. There were lots of issues with math symbols in that. The bulk of those got fixed in ‘Libertinus Serif’ when that was forked to add a math companion font—but even there a few stragglers still need fixing. For example [this issue](https://github.com/alerque/libertinus/issues/347) that was already cross-linked above notes a couple symbol alignments that need review.

**Comment by thlinard** [comment]
I think @alerque will agree that Libertinus https://github.com/alerque/libertinus is a good reference. 😀 And STIX https://github.com/stipub/stixfonts too.

Also:
- https://github.com/YuanshengZhao/Garamond-Math
- https://www.ctan.org/tex-archive/fonts/Asana-Math/
- https://github.com/googlefonts/noto-fonts/tree/master/hinted/NotoSansMath
- https://github.com/firamath/firamath
- https://github.com/alif-type/xits

**Comment by thlinard** [comment]
Also, as there is a `case` feature and `lnum` and `onum` features in Elstob: 

For me, first, the mathematical signs must be in two sets if there is a `lnum` feature and a `onum` feature. And the math axis of the `lnum` mathematical signs  must not be different from the vertical axis of hyphen, en dash and em dash of a `case` feature (lining figures = uppercase letters).

And the math axis of `onum` math signs must not be different from the vertical axis of hyphen, en dash and em dash in their default version (oldstyle figures = lowercase letters).

**Comment by psb1558** [comment]
Teaching today, so I can't say a lot, but I'm taking all this very much to heart, and I thank everyone for their contributions. There will be two sets of operators to match lnum and onum. Thanks for the font references: I will look at all of them. I'd like very much for Elstob to get this right!

**Comment by psb1558** [comment]
The Adobe 2 set (plus empty set), with some numbers. I think I have to work on spacing.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/16215767/91559800-ba20aa80-e906-11ea-8bd2-f780d86579b1.png">

**Comment by psb1558** [comment]
Do the Greek (or Greek-like) symbols have italic forms? I notice that the math fonts don't bother much with italics.

**Comment by thlinard** [comment]
Not exactly. The math fonts do bother much with italics, but not for the same purpose and in the same use than common fonts. So, Greek-like has italics forms, indeed.

To quote http://www.typoma.com/publ/20041002-atypi.pdf:

> Basic Requirements for a Text Font
> The most important font in math is Italic.
> - Italic should be really italic (not oblique Roman)
> - have letterforms clearly distinct from Roman: (…)
> - have a distinct slant: (…)

> Math Italic
> It is preferable to use a special, slightly wider Math Italic.
> - Better separation of text and math.
> - Kerning of Math Italic is different. Each letter should be read as a single letter, not as part of a word: (…)
> - Math Italic could be 5–10% wider.
> - In some fonts the next greater width can be used.

> Greeks
> - Mathematics needs a complete set of Greek letters.
> - The same 4 designs are needed as for Latin: Roman, Italic, Bold, Bold Italic

> Special Letterforms
> Some Italic letterforms need special attention:
> - (…)
> - upright and italic “delta”:

> Basic Math Glyphs
> **Most OpenType fonts contain a few math characters. (…)**
> **always upright, never italic/oblique/slanted:**
> (…) **∏ ∑**
> (…) **both upright and italic: ∂ μ π ∆ Ω**
> one form only (either upright or slanted): ∫√

> Problematic Glyphs
> (…) upright and italic “partialdiff” must be different

> Font Usage in Mathematics
> Italic is used for
> - variable (…)
> - functions and operators (…)
> - quantities and constants in physics
> Bold Italic: mainly for vectors and matrices

**Comment by psb1558** [comment]
Very useful, Thomas: thank you! (And it's a relief that there aren't a whole lot of italics to make.)

Tentatively, this is the collection of additions and revised glyphs. Operators from Adobe 2:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/16215767/91621178-35627a80-e960-11ea-995b-b25c14f312b2.png">
A sampling with different figure sets:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/16215767/91619990-b28bf080-e95c-11ea-8138-0ec0defd7d43.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/16215767/91620827-12839680-e95f-11ea-97ea-336f2bfa23be.png">
Letterlike:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/16215767/91620990-8d4cb180-e95f-11ea-89da-71210ecccc52.png">
For linguists:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/16215767/91621534-54154100-e961-11ea-9596-6bf62e4d7afd.png">
The subscript numbers behave like the superscript: they are responsive to onum, lnum and zero. Also a superscript plus and an alternate asterisk to harmonize with it:
<img width="96" alt="image" src="https://user-images.githubusercontent.com/16215767/91621622-b0786080-e961-11ea-8287-6de97f0a36ef.png">
The asterisk will match the plus if the same OT features are applied to it.

Anything mentioned in this thread that is not in Elstob will be included in JuniusX.

**Comment by thlinard** [comment]
Very good! But isn't there an alignment problem for ∅?

**Comment by psb1558** [comment]
There seems to be a wide variety of treatments of ∅. Asana-Math positions it on the baseline (with undershoot), and makes it small enough that its center falls just a little bit above the math axis:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/16215767/91637034-52846100-e9d3-11ea-980a-215f4bab4065.png">
Garamond-Math doesn't worry about the math axis at all:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/16215767/91637071-8a8ba400-e9d3-11ea-9edc-fcf01959aee0.png">
XITSMath sizes it the way the other fonts do, but lowers it so it's centered on the math axis:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/16215767/91637093-c161ba00-e9d3-11ea-852c-443053952255.png">
Elstob's usage is more like that of Garamond-Math (my minus is higher because it's aligned with the "case" hyphen):
<img width="214" alt="image" src="https://user-images.githubusercontent.com/16215767/91637131-19002580-e9d4-11ea-9b3b-9fa1c7f6c9c8.png">
Is there a best practice here? And does it make a difference that it's at least as likely to be used in a linguistic as in a mathematical context?

**Comment by Cogli** [comment]
> There seems to be a wide variety of treatments of ∅. Asana-Math positions it on the baseline (with undershoot), and makes it small enough that its center falls just a little bit above the math axis:
> <img alt="image" width="222" src="https://user-images.githubusercontent.com/16215767/91637034-52846100-e9d3-11ea-980a-215f4bab4065.png">
> Garamond-Math doesn't worry about the math axis at all:
> <img alt="image" width="217" src="https://user-images.githubusercontent.com/16215767/91637071-8a8ba400-e9d3-11ea-9edc-fcf01959aee0.png">
> XITSMath sizes it the way the other fonts do, but lowers it so it's centered on the math axis:
> <img alt="image" width="235" src="https://user-images.githubusercontent.com/16215767/91637093-c161ba00-e9d3-11ea-852c-443053952255.png">
> Elstob's usage is more like that of Garamond-Math (my minus is higher because it's aligned with the "case" hyphen):
> <img alt="image" width="214" src="https://user-images.githubusercontent.com/16215767/91637131-19002580-e9d4-11ea-9b3b-9fa1c7f6c9c8.png">
> Is there a best practice here? And does it make a difference that it's at least as likely to be used in a linguistic as in a mathematical context?

Thinking about contexts where one usually find ∅, mostly alongside set relation symbols like ⊆ or ∈ or set operators, or even enclosed in brackets {}, I would say that the best is to center it with the math axis.

**Comment by thlinard** [comment]
Sounds good! On the previous screenshot, I didn't have a sense of where exactly the baseline was, but now it's OK.

**Comment by psb1558** [comment]
It's distressing to have two valued commenters/advisors disagreeing :)

What I've done is, first, make the emptyset slightly bigger so that it aligns on the math axis for lining figures:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/16215767/91641258-237ce800-e9f1-11ea-9901-f0a9dd4c55e4.png">
Second, I've made an oldstyle emptyset that aligns on the math axis for oldstyle figures. This one is smaller and sits lower; it is most suitable for linguistic use, since it will harmonize well with lowercase letters. If people use oldstyle figures in their prose, as they should, they will get it automatically:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/16215767/91641230-ef092c00-e9f0-11ea-8f41-ccc58296dbb1.png">
Its behavior is thus like that of other operators.

Italic is almost done.

**Comment by psb1558** [comment]
Italic. The standard operators are the same except for the spacing:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/16215767/91644482-58e1ff80-ea0a-11ea-9098-0c3da7f29249.png">
Old style:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/16215767/91644759-30a7d000-ea0d-11ea-8348-9f7c0b7a3b03.png">
Letterlike:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/16215767/91644921-b710e180-ea0e-11ea-843d-5b48ec6fc318.png">
(I recognize that the pi doesn't fit: I'll have to replace it.)

**Comment by Cogli** [comment]
> It's distressing to have two valued commenters/advisors disagreeing :)

Ha ha! Too generous on me!

**Comment by thlinard** [comment]
> It's distressing to have two valued commenters/advisors disagreeing :)

Oh, because I said ∅ had to be on the baseline, and @Cogli was saying in the math axis? But you have found a way to do both at the same time. 😀

**Comment by psb1558** [comment]
Well, it's the best way, because the font *could* be used for very simple math, and it has to be right for linguistics too, and the need are different.

I am very grateful for all the help I've gotten with this issue: lots of knowledgeable and constructive feedback that has made the font much more useful.

**Comment by thlinard** [comment]
> Italic. The standard operators are the same except for the spacing:
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/16215767/91644482-58e1ff80-ea0a-11ea-9098-0c3da7f29249.png">
> Old style:
> <img alt="image" width="445" src="https://user-images.githubusercontent.com/16215767/91644759-30a7d000-ea0d-11ea-8348-9f7c0b7a3b03.png">
> Letterlike:
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/16215767/91644921-b710e180-ea0e-11ea-843d-5b48ec6fc318.png">
> (I recognize that the pi doesn't fit: I'll have to replace it.)

Example of Brill and Libertinus Math (Libertinus Math doesn't have a specific Italic file, the italic characters are 𝜕 ‎U+1D715 MATHEMATICAL ITALIC PARTIAL DIFFERENTIAL, 𝛺 ‎U+1D6FA MATHEMATICAL ITALIC CAPITAL OMEGA, 𝜇 ‎U+1D707 MATHEMATICAL ITALIC SMALL MU, 𝛥 ‎U+1D6E5 MATHEMATICAL ITALIC CAPITAL DELTA, 𝜋 ‎U+‎1D70B MATHEMATICAL ITALIC SMALL PI):
<img width="311" alt="Brill" src="https://user-images.githubusercontent.com/13808824/91660527-c9565280-ead6-11ea-9656-f45daf80fdc7.png">

Brill is wrong in not differentiating ∂ "upright" and italic, but other than that it renders characters correctly, for an non-math font.

As you can see, ∏∑ are made larger than capitals, and below the baseline — almost as high as the ascender line, and as low as the descender line.

**Comment by psb1558** [comment]
I totally missed the size of Pi and Sigma, and that Sigma extended below the line, like Pi. I've redesigned italic mu and pi, and corrected the bottom curve of partialdiff in both faces.
<img width="244" alt="image" src="https://user-images.githubusercontent.com/16215767/91667493-f30d7a80-ead2-11ea-9ffc-b6fc324fe21b.png">

**Comment by psb1558** [comment]
Will users (or apps) expect to find glyphs at U+1D715, U+1D6FA, etc., or are these only expected where there's no separate italic face?

**Comment by Cogli** [comment]
> Will users (or apps) expect to find glyphs at U+1D715, U+1D6FA, etc., or are these only expected where there's no separate italic face?

I would take an un-educated guess, and say that in Elstob case it is better not to include them!
Unicode points 1D400–1D7FF are for massive mathematical typsetting, so that in just one font one could find enough variants (bold, italic, sans serif, script, fraktur...) on greek and latin alphabets, to cover for multiple stylistic and semantical needs.
In a typeface such as Elstob, which already has an italic style and different weights, and which is not primarly intended to typeset math, I would say there is no use for them.

Moreover, to include those characters would imply that in Elstob Italic those same glyphs are going to occour twice,
which is not itself an absurd, since they would actually corrispond to different unicode points, but at least...bizarre!

**Comment by thlinard** [comment]
Same glyphs at different Unicode points wouldn't be bizarre, it's very common. For example AΑА: the same glyph repeated three times, but three different characters, because semantically different (U+‎0041 LATIN CAPITAL LETTER A, U+‎0391 GREEK CAPITAL LETTER ALPHA, U+‎0410 CYRILLIC CAPITAL LETTER A).

But in the case of U+1D715, U+1D6FA, etc., where I agree with @Cogli, they're made to work with a MATH table, for software knowing how to interpret such a table (MS Word, Firefox , LuaTeX, etc.) and who are waiting for a rather complete implementation of the mathematical charset: this doesn't concern you.

**Comment by Cogli** [comment]
> Same glyphs at different Unicode points wouldn't be bizarre, it's very common. For example AΑА: the same glyph repeated three times, but three different characters, because semantically different (U+‎0041 LATIN CAPITAL LETTER A, U+‎0391 GREEK CAPITAL LETTER ALPHA, U+‎0410 CYRILLIC CAPITAL LETTER A)

True. What I was trying to point out is that, whereas Latin or Greek or Cyrillic Unicode points are style-independent, 1D400–1D7FF are not. U+1D6FA, say, is meant to be a serifed, non-bold glyph. Those characters only make sense in a not-styled font, with natural coverage for latin, greek, etc. serifed upright glyphs.

**Comment by psb1558** [comment]
Okay, thanks. I've built otf, ttf and variable fonts and put them in the font directory. If there are no issues around the math symbols after a week or so, I'll do a new release. Once again, these glyphs are added or changed (hope I'm not missing anything):
<img width="525" alt="image" src="https://user-images.githubusercontent.com/16215767/91716561-eda94200-eb5d-11ea-9c0d-8a4f1872a4c4.png">
The operators that are aligned on the math axis also have oldstyle variants (the same, but shifted down). Also added two arrows:
<img width="109" alt="image" src="https://user-images.githubusercontent.com/16215767/91717983-8c36a280-eb60-11ea-92db-4d57d5769d26.png">
and subscript figures:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/16215767/91717216-0bc37200-eb5f-11ea-9a77-a5f6977c0b4c.png">
Added a subs feature and edited lnum, onum, sups, and zero to take account of the new stuff.

**Comment by thlinard** [comment]
What is the ◊ aligned with?

**Comment by psb1558** [comment]
I just noticed that and fixed it. There are now lining and osf versions of lozenge, aligned on the appropriate math axes. This is not yet in the built fonts.
<img width="169" alt="image" src="https://user-images.githubusercontent.com/16215767/91719945-2f3ceb80-eb64-11ea-8b5c-d547aeca2b85.png">

**Comment by thlinard** [comment]
Very good!!

**Comment by psb1558** [comment]
This is done now, I think. Thanks to everyone who participated!
