### ISSUE TITLE
opsz question

### ISSUE THREAD

**Issue by Cogli** [psb1558/Elstob-font#2]
Instead of adding to x-height, wouldn't be better to subtract from capital, ascender & discender in order to keep scaling consistent?

Thank you!

**Comment by psb1558** [comment]
What I tried to do was keep the distance from baseline to ascender top consistent. Increasing the x-height automatically decreases the ascender. The descender is shortened to keep things in balance. A thorn is the best example: does this work?
![thorn-compare](https://user-images.githubusercontent.com/16215767/76615822-28a8b200-64f9-11ea-820d-31d3e984cdb4.jpg)

**Comment by Cogli** [comment]
My concern is just this: in paragraph 1 ElstobD 18 pt is in action; in paragraph 2 I scaled the text a whole point down; in par3 I changed to ElstobD 8 pt, just to lose any scaling effect in rapport to par1!
![Artboard 2@2x-100](https://user-images.githubusercontent.com/55837580/76642434-7f42da00-6553-11ea-8af3-a2d181175abf.jpg)
I'm a total amateur and I really don't know anything about approaching optical sizes issue! Maybe is really just one desiderable point of opsz to make text look bigger, when scaling down.

Once again, thank you for your fonts and all!

**Comment by psb1558** [comment]
Okay, I think I see what you mean. Optical size isn't about scaling, exactly, but rather finding the optimal character-shape for particular sizes. If you were to set your par3 next to par1 (instead of two pars below), you'd see a marked difference. Here's a little experiment showing what happens when you don't match (or at least approximate) actual to optical size. For text set at 18pt, it's best to use the optical size "18pt." If you use "6pt" at that size, you see how the letter-shapes get thick and blocky. Use the "8pt" optical size at the actual size of 8pt, and you get reasonably legible text. Use "18pt." at that same size, and you lose a little legibility (on Windows machines you might even get "drop-out" of thin strokes).
![opsz-demo](https://user-images.githubusercontent.com/16215767/76648716-94a90b80-6535-11ea-861f-e514143e55b5.jpg)

**Comment by Cogli** [comment]
Generally speaking, increasing x-height entails a bigger perceived size. That is what was bothering me. I was wondering whether one could find the optimal characters shape without altering – so to say – "perceived scale proportions" between blocks of text.

Anyway, I'm about to learn that in some typefaces smaller opsz are obtained by increasing x-height (amongst other things), in others are obtained by decreasing ascenders line and capital heigth. It's all up to designers'choice, afterall! And to final users taste and ability to take advantage of those choices.
![Artboard 4@4x-100](https://user-images.githubusercontent.com/55837580/76656606-4a914b80-6570-11ea-9289-5cd0342d07ca.jpg)

**Comment by psb1558** [comment]
Yeah, unfortunately there is no uniform rule about making optical size variants. I prepared for that part of this project by reading Ahrens and Mugikura, _Site-specific adjustments fo type designs_ (2014), and my takeaway was that there were lots of right ways to do it--and undoubtedly lots of wrong ways too! Ultimately the best solution might be to do it as a parametric font, like Amstelvar, so that things like x-height, descender-length, stem width on various dimensions can be controlled separately. Then every user can adjust to their own taste. But it may be a while before I muster the energy for a project like that.

**Comment by Cogli** [comment]
Type design is sure a super technical area, and we can only expect it's going to be even more...
To my uneducated eye you're a top-class, all the more considering you're not a pro!

Ok, thanks for all and keep up the good work!
