### ISSUE TITLE
add vietnamese support

### ISSUE THREAD

**Issue by tommai4881** [psb1558/Elstob-font#22]

**Comment by Alice196498** [comment]
I agree that Vietnameſe ſupport would be nice, but the language does have ſome unique technical challenges, which are talked about in detail on [this page.](https://vietnamesetypography.com/introduction/) Reading through it, one can get a rather good idea of the kinds of things needed for ſupport of the language, and ſolutions to the deſign challenges it poſes.

**Comment by psb1558** [comment]
I'll think about this. I omitted a lot of languages from Elstob to keep it as small as possible, but Vietnamese (though the rules are complex) wouldn't add much to the size of the font.

**Comment by psb1558** [comment]
Try out any of the fonts in fonts/ttf, fonts/otf, or fonts/variable. Comments very welcome.

**Comment by Alice196498** [comment]
I’m trying out the variable verſions now, and they ſeem to work rather well. Technically, the dot ought to be preſerved with the letter i and diacriticks, and if poſſible, I ſhould recommend that it be preſerved. While it is generally recommended to put both acute and grave accents to the right, putting them on each ſide according to the ſlope is not incorrect, and can help with diſtinguiſhing the tones ; thus I think it’s a good deciſion, but I’d like to hear what people more familiar with the language have to ſay in regard to readability.
 I alſo notice that ss08 doeſn’t ſeem to take into account the new vowels in the Italick, but it does in the Roman face, falling under the default ſet. It might be beſt that ầ, ề, and ồ get a ſhort s before them, as they collide, as well as before all diacritick i variants, except maybe ị, which could be ligated, perhaps, as ſi is. Looking at what ſome early printers did, they ſeem to do things a little differently than one might expect, but ſeeing as it’s difficult to find books from this era, we could either follow their example to the beſt of our diſcernment, or we could follow our own ſenſibilities, or we could have a blending of the two.

**Comment by psb1558** [comment]
I've got fonts with the grave accent on the right, left, and top of the circumflex, but I like the position on the left best. I haven't got any fonts that retain the  i dot when Vietnamese diacritics are added: what are you looking at?

There's a fair amount of work to do to get the new characters working with the font's OT features, and there are small caps to be made and kerning to be done. It's all on the to do list.

**Comment by Alice196498** [comment]
I like the grave on the left too, and think it’s a good idea.

As for the tittle on the lowercaſe i, the [deſign challenges](https://vietnamesetypography.com/design-challenges/) page here talks about it at the bottom. It’s true that moſt digital typefaces don’t keep the dot, but as far as I know, it’s technically ſuppoſed to be there. [This Language Log](https://languagelog.ldc.upenn.edu/nll/?p=4233) alſo mentions it, but confines the retention of the dot to handwriting, and the [Wikipedia page](https://en.wikipedia.org/wiki/Tittle) of the tittle ſtates :—
 “ In [Vietnameſe](https://en.wikipedia.org/wiki/Vietnamese_language) in the 17th century,[[11]](https://en.wikipedia.org/wiki/Tittle#cite_note-De_Rhodes_1641-11) the tittle is preſerved atop ỉ and ị but not ì and í, as ſeen in the ſeminal quốc ngữ reference [Dictionarium Annamiticum Luſitanum et Latinum](https://en.wikipedia.org/wiki/Dictionarium_Annamiticum_Lusitanum_et_Latinum). In modern Vietnameſe, a tittle can be ſeen in ì, ỉ, ĩ, and í in curſive handwriting and ſome ſignage. This detail rarely occurs in computers and on the Internet, due to the obſcurity of language-ſpecifick fonts. In any caſe, the tittle is always retained in ị.”
 Thus, I ſhould think that this feature is technically correct, but is often left out of digital typefaces either for hiſtorical difficulties, convenience, or a general lack of proper language ſupport ; therefore, in the ſpirit of having the beſt ſupport and care poſſible in relation to each language, I believe that it would be nice to keep the tittle.

I did notice the ſmall caps and kerning, but a bit after making my initial comment I’m glad that they’ll be included too.

**Comment by psb1558** [comment]
Vietnamese now uses a flatter shape of acute, grave, and circumflex in the lowercase, easing problems with line spacing (roman variable font only; italic will follow shortly). Make sure the language is set properly in whatever application you're using.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/16215767/182720304-e2516fc0-be63-493e-ac47-6461ad1f64b3.png">

**Comment by psb1558** [comment]
Default forms of i, with Vietnamese language set:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/16215767/182762537-68790a1a-9acf-4c05-90a6-6ccfd2c383cb.png">
In Junicode, ss09 is reserved for language-specific variants (of which there aren't any yet). But here is one. With Vietnamese language set and ss09 on:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/16215767/182762692-f06626f6-b915-4e7d-bab5-218a3cd80c06.png">

**Comment by Alice196498** [comment]
Ooh, I like the changes you’ve made here. I alſo notice that the hook on ơ and ư has been made a bit more prominent, which is ſomething I wanted to comment on, but didn’t get a chance to mention. It feels very even, harmonious, and that the diacriticks have equal importance to the letters, at leaſt to my eyes.

I alſo very much like your ſolution with ss09 ! That looks lovely, and alſo makes this one of the few, if not the only, typefaces that actually pays attention to this aſpect of Vietnameſe typography.

**Comment by psb1558** [comment]
This is done, I think.
