### ISSUE TITLE
Long ſ in Norwegian

### ISSUE THREAD

**Issue by sigurdhasle** [psb1558/Elstob-font#30]
I tried to print words starting with s and any other letter using ss08 in Norwegian. All the words started with a long ſ – exept the word continuing with an f. I am quite convinced that «ſfære» («sphere») should start with a long ſ.
And «Prinſeſſen»! We do not use «ſſ» in Norwegian – it is sſ inside words, and ſs in the end – «Prinſesſen»! I can mend this by inserting a soft hyphen, but it would be nice if this was automatic.
Is this something that can be changed?

(I am impressed by «Skipsfolkenes» which should not have a long ſ because it is a compound word. And it does not!)

**Comment by psb1558** [comment]
Elstob has no rules for Norwegian. If you can point me to a comprehensive set of rules for that language, I'll figure out if OpenType programming can render them.

**Comment by sigurdhasle** [comment]
I fear that I do not know where to find comprehensive rules for Norwegian – but I think they are quite similiar the rules for English with the exeptions I mention –  at least the one i am completely sure of: sſ inside words, and ſs in the end. Can you copy the English rules with my exeptions and use them for Norwegian? I am sure someone will tell you if they find that something else is missing.

**Comment by Alice196498** [comment]
I’ve talked a bit about the rules for Scandinavian languages in the [long s thread here](https://github.com/psb1558/Elstob-font/issues/23). Norwegian, along with Swediſh and Daniſh, generally follows the rule of having a ſhort s at the end of a compound element, and at the end of words, with long s uſed elſewhere. The general method works rather well, but miſſes the compound element rule becauſe it’s not ſomething that can eaſily be implemented without a ſpecial heuriſtick, which would need to be deſigned. I did look into both ſfære and ſfär, and while I was only able to find blackletter examples, they did indeed have long s at the beginning. Antiqua generally tries to avoid long s next to an f, but I have ſeen ſome inſtances when reſearching for the Scandinavian languages ; thus, it’s not neceſſarily incorrect there, but may be compound-dependent. Elſtob can do that combination, technically, but there’s no way to do it automatically, and as there is no way to force a long s, the automatick method in ss08 fails to account for this. If you want to force a ſhort s, it can be done with the Zero Width Non-Joiner, U+200C, ſet after it. Perhaps ſetting this before the letter could force a long s in order to allow for manual or dictionary-baſed corrections.

As for _Prinſeſſen,_ the ſpelling you indicate is uſually found in Dutch, which uſes ſyllable rules, rather then word-compound rules. In the Scandinavian languages, a double long s is generally uſed, as you’ll ſee in the following books :
https://www.google.com/books/edition/Fors%C3%B6g_til_en_Skilding_af_quindekj%C3%B6nne/YtxAAAAAcAAJ?hl=en&gbpv=1&dq=Prinsessen&pg=PA91&printsec=frontcover
https://www.google.com/books/edition/Swea_rikes_historia/sMIFAAAAQAAJ?hl=en&gbpv=1&dq=prinsessan&pg=PA499&printsec=frontcover
https://www.google.com/books/edition/Historia_om_England_ifr%C3%A5n_Julii_C%C3%A6sars/LqCAdM7_7kQC?hl=en&gbpv=1&dq=prinsessan&pg=PA156&printsec=frontcover
https://www.google.com/books/edition/Kungl_Vitterhets_Historie_Och_Antikvitet/w_8ZAQAAIAAJ?hl=en&gbpv=1&dq=prinsessan&pg=PA165&printsec=frontcover
https://www.google.com/books/edition/F_rs_k_til_et_biographiskt_lexicon_fver/IxuOheI-xa0C?hl=en&gbpv=1&dq=prinsessan&pg=PA234&printsec=frontcover

That being ſaid, I have ſeen ſome examples of the sſ ſpelling in a couple of books—I wouldn’t ſay it’s _wrong,_ but from what I can tell, it’s not the moſt common way of doing things in theſe languages, while it is an option. For the automatick replacement, I perſonally feel it’s beſt to follow the moſt widely accepted practice.

The beſt way to handle the Scandinavian languages at the moment is to apply the general long s rules, which is what the typeface does currently, and then apply your own fixes with the ZWNJ to force a ſhort s where needed. For the caſes where a long s ſhould appear but doeſn’t, that muſt be done without SS08, unfortunately. It’s not a perfect ſolution, but it works well in moſt caſes. It may be poſſible to develop an heuriſtick as a baſe to try and catch more caſes, but that would require a good dictionary in theſe languages as well as ſome analyſis to determine a way of programming the rules in a ſimple way. There does exiſt a ſimilar ſyſtem in the German Unifraktur typeface, which manages to catch moſt caſes, but it is imperfect. This method could, perhaps, be improved upon with ſome additional rules after the initial heuriſtick is run to catch exceptional words.

**Comment by sigurdhasle** [comment]
Thank you! This is intereſting! You are right – and you are wrong. I thought that we did not uſe double ſ in Norwegian – but your ſources clearly ſhow that we did.

I think the point is that the rules have changed from the 17-1800s to the 1900s. I checked the firſt Norwegian newspaper: «Norſke Intelligenz-Seddeler» from 1763, and here I find – like you ſaid – the double-ſ in words like «glaſſeret», «Paſſager», «adreſſere».

But when I look at «Aftenpoſten» from 1912 – juſt before they ſwitched from fraktur to antiqua – i do not find the double ſ. They print «disſe», «erfaringsmæsſig» «Pasſager», «Dagspresſen» and «interesſerede».

The example i often use to ſhow the sſ is the head of the oldeſt Norwegian newspaper Adresſeaviſen https://www.adressa.no/ (But it ſtarted as «Tronhjems Adreſſe-Contoirs Efterretninger» with ſſ.) https://www.nb.no/items/f57025cb30dbea5d81548ac2bf6d21a7

I am trying to replicate an old fairytale from Asbjørnsen and Moe from 1852 – https://www.nb.no/items/73090552b88065ea16eaef4cc18b3042?page=0&searchText=prindsessen

At that time they uſed sſ. So I think we have to decide whether to uſe ſſ or sſ depending on what rules they uſed at the time of the document you are making.

I ſee that I can force the round s by adding a ſoft hyphen after the s – the program underſtands that this is the laſt letter of the word. (And if the word happens at the end of the line it wil be separated correctly: «Prindſes-ſen».) I can also force a long ſ by ſimply inſerting a long ſ.

**Comment by Alice196498** [comment]
Oh, this is quite intereſting, then. You’re right that both ſſ and sſ appear in medial poſition, and in words that would be unexpected. From what I can tell, it ſeems that there was a change in the rules over the courſe of the 1800s—it looks like the original rule was that ſſ is uſed unleſs it’s a word-compound. Then it changed to write sſ always in medial poſition.

Given that, in my opinion, the beſt ſolution is to retain ſſ, keeping with the old way in general, and uſe the ZWNJ, or, as you are doing, a ſoft hyphen to employ the newer ſtyle. That would be more verſatile for general uſers, at the unfortunate coſt of more effort if they ſhould deſire to ſet in the new ſtyle, rather than the older.

My Norwegian iſn’t great, but perhaps you could find ſome references to the rules if any printers over the centuries wrote anything about it. In Engliſh, pretty much no one wrote anything down, and I’m the only perſon to have completely documented the rules and rational for them—the only other attempt I’ve ſeen is from Babelſtone, but it left out a couple of details and didn’t really explain why the rules were as they were. In German, the rules are well-documented, which is convenient. Perhaps Norwegian, Daniſh, or Swediſh have the rules written ſomewhere, or at leaſt an explanation or documentation of the ſhift from ſſ to sſ word-medially. If you’d be willing, I’d like to work with you further to more clearly and concretely determine the rules for theſe languages : the better documentation available, the eaſier it is to implement. If we can determine the rules, it may be poſſible to automate them or deſign an heuriſtick that can account for things to the beſt of its ability.

**Comment by sigurdhasle** [comment]
I am not really an expert (of a typographer) – but I can try to find ſome references to the rules for Scandinavian.

(On the other hand, I think it was uſual to drop the long ſ completely in antiqua around1800. So the «new» rule (sſ) may really apply only to fraktur.)

**Comment by psb1558** [comment]
The reason there are so few languages for which Elstob has long-s rules is that the kind of programming you can embed in a font is so extremely limited. There is no possibility of any font recognizing morpheme boundaries: this is not the kind of job the OpenType font format was designed to take on. So rules for long-s in German, for example, are out of the question, as font designers generally recognize.

With English, French, Italian and Spanish we get lucky, because in those languages we can construct rules based on a context of a very few letters: an **f** preceding or following, a **b** or **h** following, etc. If it is possible to come up with an equally simple set of rules for Norwegian, then I can add it. But it doesn't sound like Norwegian is the kind of language for which that is practical. Things that are impossible or impractical in an OpenType font can, however, often be accomplished with a few lines of JavaScript.

I will mention, too, that at present my attention is taken up with other matters, and I can't research these things myself. I can add rules devised by others, if practical, but that work, and the subsequent testing, may be slow.

**Comment by Alice196498** [comment]
The medial sſ rule moſtly applies to Fraktur, but I have ſeen it in a couple of Antiqua books. It’s not unheard of, but it was, hiſtorically, leſs common than ſſ prior to the 1800s, when sſ ſtarted to become more prevalent. Given that it’s not ſimple to define a perfect ruleſet for Norwegian, or the other Scandinavian languages, it’s beſt to keep the general rule in place, and then edit the text yourſelf. I’d live if an automatick ſyſtem could be applied, but ſetting a liſt of rules that work correctly at the very leaſt even in moſt caſes would be difficult. Perhaps with a good corpus wordliſt and marking the compound words correctly, it would be poſſible to do text analyſis on the corpus and programatically ſearch through and uſe whatever patterns it finds to define a liſt of rules, but that iſn’t very eaſy to do for everyone. I have a general idea how it might be done, but I don’t know exactly how to do it myſelf, otherwiſe I would.

I did write out the rules for a couple of other languages—it would be poſſible to add Portugueſe, Vietnameſe, and Scottiſh Gaelick, becauſe the three of thoſe follow ſimple & practical to implement rules like the other defined languages.

I do hope that the other matters which are taking your attention go well. Reſearching theſe things is ſomething I can do and help with, and I can help with teſting : I’m happy to do ſo, becauſe this is a great typeface ; in fact, I’d ſay it’s one of the beſt in general, and the beſt in regard to certain features that only exiſt in it at the moment.

**Comment by sigurdhasle** [comment]
I see now that the long ſ-rules I know applied to fraktur in 1852 and 1912. I have to try to find out what the correct rules were for antiqua before they dropped the long ſ.

When I want to use «my» rules I can use ss08 to get s and ſ right in almost all cases, and I can correct the rest by inserting soft hyphens.

Thank you very much for all the good work!
