### ISSUE TITLE
Not available on Homebrew

### ISSUE THREAD

**Issue by dei-layborer** [psb1558/Elstob-font#33]
Pretty much what the subject says.  The documentation says to install via Homebrew, but it doesn't seem to be available.  The closest thing I was able to find is the cask ``font-elstobd``, but it 404s on trying to install.

**Comment by psb1558** [comment]
The person who maintained the package must have bailed. I'll take Homebrew out of the documentation.

**Comment by alerque** [comment]
Elstob is still provided, the entire Homebrew font system just split all the fonts out of the main repository and moved them into the homebrew-cask-fonts collection:

https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-elstobd.rb

The issue seems to be that *this project* changed out the release artifact after initial release (an `a` was appended to the ZIP name.

I suggest rather than dropping the documentation somebody (it can be anybody) just submits a PR to the above linked file that updates the source URL to the one [attached to the release](https://github.com/psb1558/Elstob-font/releases/tag/v1.015).

Also in the future don't re-post assets to releases! Bump the version and add a new release tag if something goes wrong with the release pipeline, otherwise you end up with downstream breakable like this.

**Comment by alerque** [comment]
Note as the Arch Linux packager for this font after reading this issue I went and checked, and our AUR package is broken for the same reason. The originally posted asset is missing and one must append `a` to the URL to get it. I updated the AUR recipe.

**Comment by psb1558** [comment]
Did I really do that? Sorry!

I'm not sure I understand how to correct the problem. If no one else does it, I'll just make a new release in a few days. I believe I've made enough small changes in the last year to justify a new version number.

**Comment by alerque** [comment]
There are very few "right" ways to fix this. To unbreak existing distro packaging that relies on the asset being available, the asset must be replaced. In this case that would mean attaching the original zip file without the "a" to the release. Note that more the name is important, bit must be the same file because packaging usually includes a checksum to make sure sources don't change. If you don't have the original file to replace that's going to be hard to do, and presumably you had a reason for the "a" variant in the first place. The other option where we are at now is each packaging recipe needs to be fixed with the new asset name and checksum. I've already done that for Arch Linux. Somebody can do so for Homebrew and any others out there. No change on your part is probably better than trying to revert and bungling it with the wrong file or something.

A new release would be welcome too. Even with minimal changes. Minor version bumps with no changes to packaging are the easiest things to get though distro packaging :-)

**Comment by psb1558** [comment]
That earlier file no longer exists, so no fix there.

I'm adjusting some kerning right now. When that's done, I'll make a new release (with new version number). And I've learned something important about how packaging works in Linux and Homebrew.

**Comment by psb1558** [comment]
There's now a new release, version 2.100, with a different zip file.

**Comment by alexmyczko** [comment]
are you aware of `brew install fnt`, and `fnt update; fnt install elstob` ?

**Comment by alerque** [comment]
> are you aware of `brew install fnt`, and `fnt update; fnt install elstob` ?

I for one was not. It certainly looks like a tool with some utility, but also with some drawbacks. Instead of being one step removed from upstream releases it is two: it relies on Debian font packages or Google Fonts to source from and can't be updated independently of those channels. Both have various issues with updating some fonts. Neither are very friendly to fonts that see ongoing development (Google Fonts being the worse of the two in that respect).

In the meantime the Homebrew native font cask for Elstob is up to date and can be installed with the usual:

```console
$ brew tap homebrew/cask-fonts         # You only need to do this once!
$ brew install font-elstobd
```

...and with that I also suggest this issue can be closed since the original issue is resolved.

**Comment by dei-layborer** [comment]
Confirmed that it now installs properly via Homebrew with the above instructions.  It also installed the up-to-date version (2.1), which was not the case with ``fnt``.

Closing the issue since it works now.  Thanks everyone!

**Comment by psb1558** [comment]
Very glad to hear this!
